config/routes.rb
OLM::Application.routes.draw do
  get "users/user"
  get "books/index"
  get "dashboard/index"
  get "static_pages/contact"
  get "static_pages/about"
  get "static_pages/faq"

  get "welcome/index"

  root 'welcome#index'

  get 'users/account' => 'users#account'
  post 'users/editaccount' => 'users#editaccount'
  get 'users/:new' => 'users#new'
  get 'login/:new' => 'login#new'
  post 'login/:new' => 'login#create'
  delete 'login/:new' => 'login#destroy'
  delete '/#' => 'login#destroy'

  get 'upload/pdfview' => 'upload#pdfview'
  get 'upload/fileform' => 'upload#fileform'
  get 'upload/search' => 'upload#search'
  post 'upload/fileupload' => 'upload#fileupload'

  get '/contact' => 'contact#new'
  post '/contact' => 'contact#create'

  Rails.application.routes.draw do
  resources :users # or resource :user for singular resources
  resources :login
  end

  namespace :admin do
    get "manage_users/list", to: 'manage_users#list', as: '/manage_users/list'
    get "manage_books/list", to: 'manage_books#list', as: '/manage_books/list'
    get 'dashboard/index', to: 'dashboard#show', as: '/'
    post 'manage_users/list'
    get 'add/new'  => 'add#new'
    post 'add/new' => 'add#create'
    post 'manage_books/list'
    post 'manage_books/delete'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates_presence_of :title, :on => :create
	validates_presence_of :author, :on => :create
	validates_presence_of :book, :on => :create
	validates_presence_of :cover, :on => :create

	def self.search_title(search)
		if search
			find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end

	def self.search_author(search)
		if search
			find(:all, :conditions => ['author LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_presence_of :first_name, :on => :create
	validates_presence_of :last_name, :on => :create
	validates_presence_of :zip, :on => :create
	validates_presence_of :username, :on => :create
	validates_presence_of :email, :on => :create
	validates_length_of :last_name, :maximum => 30, :message => "last name to long!"
	validates_length_of :first_name, :maximum => 15, :message => "first name to long!"
	validates_length_of :username, :within => 6..20, :too_long => "pick a shorter name", :too_short => "pick a longer name"
    validates_length_of :zip, :minimum => 5, :too_short => "please enter at least 5 characters"
    validates_length_of :password, :minimum => 8 ,:maximum => 32, :within => 8..32,:too_short => 'way too short', :too_long => 'way to long'
    validates_uniqueness_of :username, :email, :case_sensitive => false
end

app/controllers/admin/add_controller.rb
class Admin::AddController < ApplicationController
  def new
    if current_user != nil && current_user.admin?
      @admin = User.new
    else
      redirect_to root_path
    end
  end

  def create
	  if current_user != nil && current_user.admin?
	    def my_params
	      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country, :admin)
	    end 
	    @admin = User.new(my_params)
	    @admin.admin = true;
	    if @admin.save
	      redirect_to "/admin/dashboard/index", :notice => "Signed up!"
	    else
	      render "/admin/add/new"
	    end
	   end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
 def show
    if current_user != nil && current_user.admin?
      render "/admin/dashboard/index"
    else
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #force_ssl
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
  	@badForm=false;
  	user = User.find_by_email(params[:email])
  	if user == nil
  		user = User.find_by_username(params[:email])
  	end
	if user && user.authenticate(params[:password])
	  @badForm=false;
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Logged in!"
	else
	  @badForm=true;
	  flash.now.alert = "Invalid email or password"
	  render "new"
	end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def faq
  end
  
  def about
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def pdfview
		@book = Book.find(params[:id])
	end

	def search
		@title_books = Book.search_title(params[:q])
		@author_books = Book.search_author(params[:q])
	end

	def fileupload
		uploaded_io = params[:book]
		uploaded_io2 = params[:cover]
		File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb+') do |file|
			file.write(uploaded_io.read)
		end
		File.open(Rails.root.join('public', 'uploads', uploaded_io2.original_filename), 'wb+') do |file|
			file.write(uploaded_io2.read)
		end

		book_params = {
			:title => params[:title],
			:author => params[:author],
			:book => params[:book].original_filename,
			:cover => params[:cover].original_filename,
		}

		book = Book.new(book_params)

		if book.save
			redirect_to "/upload/pdfview?id=" + String(book.id)
		else
			render "fileform"
		end
	end

	def fileform
		@message = "Hello, World!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit]

  def account
    @user = current_user()
    if @user == nil then
      redirect_to "/"
    end
  end

  def update
    @user = current_user()
    if @user == nil then
      redirect_to "/"
    end
    def user_params
      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country)
    end
    @user = User.update(params[:id], user_params)
    render "account"
  end

  def new
    @user = User.new
  end

  def create
    def user_params
      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country)
    end
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/add_helper.rb
module Admin::AddHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/manage_users_helper.rb
module Admin::ManageUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/add/new.html.erb
<div class="container">
  <div class="row">
    <div class="span2"></div>
    <div class="span8">
      <div class="well well-small wellBlue">
        <h3 class="text-center">Register for OLM</h3>
      </div>
      <div class="well well-small text-center wellBlue">
      <%= form_for @admin, :url => admin_add_new_path do |f| %>
        <% if @admin.errors.any? %>
          <div class="error_messages">
            <h3>Form Has Errors</h3>
            <ul>
              <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Warning!</strong> 
                <ul>
                  <% for message in @admin.errors.full_messages %>
                    <p><%= message %></p>
                  <% end %>
                </ul>
              </div>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :"First Name" %><%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :"Last Name"%>
          <%= f.text_field :last_name, :class=>"form-horizontal" %>
        </div>

        <div class="field">
          <%= f.label :"Country"%>
          <select id="country" name="admin[country]">
          <option value="Afghanistan">Afghanistan</option>
          <option value="Albania">Albania</option>
          <option value="Algeria">Algeria</option>
          <option value="Andorra">Andorra</option>
          <option value="Antigua and Barbuda">Antigua and Barbuda</option>
          <option value="Bahamas">Bahamas</option>
          <option value="Bahrain">Bahrain</option>
          <option value="Bangladesh">Bangladesh</option>
          <option value="Barbados">Barbados</option>
          <option value="Belarus">Belarus</option>
          <option value="Belgium">Belgium</option>
          <option value="Belize">Belize</option>
          <option value="Botswana">Botswana</option>
          <option value="Burkina Faso">Burkina Faso</option>
          <option value="Burundi">Burundi</option>
          <option value="Cambodia">Cambodia</option>
          <option value="Cameroon">Cameroon</option>
          <option value="Canada">Canada</option>n>
          <option value="Chad">Chad</option>
          <option value="Chile">Chile</option>
          <option value="China">China</option>
          <option value="Cyprus">Cyprus</option>
          <option value="Czech Republic">Czech Republic</option>
          <option value="Denmark">Denmark</option>
          <option value="Djibouti">Djibouti</option>
          <option value="Dominica">Dominica</option>
          <option value="Dominican Republic">Dominican Republic</option>
          <option value="Ecuador">Ecuador</option>
          <option value="France">France</option>
          <option value="Germany">Germany</option>
          <option value="Japan">Japan</option>
          <option value="Malta">Malta</option>
          <option value="Mexico">Mexico</option>
          <option value="Russian Federation">Russian Federation</option>
          <option value="Solomon Islands">Solomon Islands</option>
          <option value="Somalia">Somalia</option>
          <option value="South Africa">South Africa</option>
          <option value="Timor-leste">Timor-leste</option>
          <option value="Togo">Togo</option>
          <option value="Tokelau">Tokelau</option>
          <option value="Tonga">Tonga</option>
          <option value="Trinidad and Tobago">Trinidad and Tobago</option>
          <option value="Tunisia">Tunisia</option>
          <option value="Turkey">Turkey</option>
          <option value="Turkmenistan">Turkmenistan</option>
          <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
          <option value="Tuvalu">Tuvalu</option>
          <option value="Uganda">Uganda</option>
          <option value="Ukraine">Ukraine</option>
          <option value="United Arab Emirates">United Arab Emirates</option>
          <option value="United Kingdom">United Kingdom</option>
          <option value="United States">United States</option>
          <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
          <option value="Uruguay">Uruguay</option>
          <option value="Uzbekistan">Uzbekistan</option>
          <option value="Vanuatu">Vanuatu</option>
          <option value="Venezuela">Venezuela</option>
          <option value="Viet Nam">Viet Nam</option>
          <option value="Virgin Islands, British">Virgin Islands, British</option>
          <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
          <option value="Wallis and Futuna">Wallis and Futuna</option>
          <option value="Western Sahara">Western Sahara</option>
          <option value="Yemen">Yemen</option>
          <option value="Zambia">Zambia</option>
          <option value="Zimbabwe">Zimbabwe</option>
          </select>
        </div>

        <div class="field">
          <%= f.label :"School"%>
          <select id="school" name="admin[school]">
          <option value="ASU">ASU</option>
          <option value="Berkley">Berkley</option>
          <option value="Cal Tech">Cal Tech</option>
          <option value="Dartmouth">Dartmouth</option>
          <option value="Ellington">Ellington</option>
          <option value="FSU">FSU</option>
          <option value="Graham">Graham</option>
          <option value="Harvey Mudd">Harvey Mudd</option>
          <option value="ISU">ISU</option>
          <option value="John Hopkins">John Hopkins</option>
          <option value="KSU">KSU</option>
          <option value="LSU">LSU</option>
          <option value="MIT">MIT</option>
          <option value="NSU">NSU</option>
          <option value="OSU">OSU</option>
          <option value="Princeton">Princeton</option>
          <option value="Quail Canyon">Quail Canyon</option>
          <option value="Redmond">Redmond</option>
          <option value="SLU">SLU</option>
          <option value="RSU">RSU</option>
          <option value="TSU">TSU</option>
          <option value="USC">USC</option>
          <option value="Valvista">Valvista</option>
          <option value="Wash U">Wash U</option>
          <option value="York Town">York Town</option>
          </select>
        </div> 
         <div class="field date_select">
         <%= f.label :"Date of Birth" %>
          <%= f.date_select :birth, {:prompt => { :day => 'Day', :month => 'Month', :year => 'Year'}, :start_year=>1950}, {:class => 'date-select'}%>
        </div>
        <div class="field">
         <%= f.label :"Zip Code" %>
          <%= f.text_field :zip %>
        </div>
         <div class="field">
          <%= f.label :"User Name" %>
          <%= f.text_field :username %>
        </div>
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <br></br>
        <div class="actions"><%= f.submit %></div>
      <% end %>
      </div>
      </div>
      <div class="span2"></div>
    </div>
</div>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="span2"></div>
    <div class="span8">
      <div class="well well-small wellBlue">
        <h3 class="text-center">Admin Panel</h3>
      </div>
      <div class="well well-small text-center wellBlue">
	<div id="user_nav">
		 <h4> Manage Users or Books Here!! </h4>
		  <p></p>
		  <table align="center" cellpadding="20px">
		  	<tr>
		  		<td><%= button_to "Manage Users", "/admin/manage_users/list"%></td><td><%= button_to "Manage Books", "/admin/manage_books/list"%></td>
		  		<td><%= button_to "Add Admin", {:controller=> "/admin/add", :action=> "new"}, :method => :get%></td>
		  	</tr>
		  </table>
	</div>
	<div class="span2"></div>
	</div>
	</div>
	</div>
</div>

app/views/contact/new.html.erb
<div class = "container">
	<div class = "row">
		<div class = "span5">
			<div class="well well-small">
				<h3>  Contact Us</h3>
				<ul class="nav nav-list"></ul>
				 </div>

	
				<div class="well well-small">
				 <address>
				  <strong>OLM, Inc.</strong><br>
				  777 Random Ave, Suite 666<br>
				  Tempe, Az, 85284<br>
				  <abbr title="Support">P:</abbr> (123) 456-7890
				</address>
				  <table class="table">
					  <thead><th>Founder</th> <th>Email</th> <th>Number</th></thead>
					   <tbody>
					    <tr>
					      <td>David Dunning</td>
					      <td>dcdunnin@asu.edu</td>
					      <td>(480)208-3077</td>
					    </tr>
					    <tr>
					      <td>Shantanu Bala</td>
					      <td>shantanu@asu.edu</td>
					      <td>(480)242-0876</td>
					    </tr>
					    <tr>
					      <td>Antonio Franchini</td>
					      <td>afranchi@asu.edu</td>
					      <td>(480)202-8084</td>
					    </tr>
					  </tbody>
				  </table>
			</div>
		</div>
		<div class = "span7">
			<div class="well well-small">
				<h3>Any Questions?</h3>
				<ul class="nav nav-list"></ul>
				 </div>
			<div class="well well-small">
				 <%= form_for @message, :url => contact_path do |form| %>
				  <fieldset>
				  <label class="control-label" for="inputIcon">Name</label>
					  <div class="controls">
					    <div class="input-prepend">
					      <span class="add-on"><i class="icon-user" ></i></span>
					      <input class="span3" id="inputIcon" type="text" placeholder="John Smith" name="message[name]">
					    </div>
					  </div>
				    <label class="control-label" for="inputIcon">Email address</label>
					  <div class="controls">
					    <div class="input-prepend">
					      <span class="add-on"><i class="icon-envelope" ></i></span>
					      <input class="span3" id="inputIcon" type="text" placeholder="example123@email.com" name="message[email]">
					    </div>
					  </div>
				    <label>Nature of Email</label>
				    <select class ="span4" select id="subject" name="message[subject]">
					  <option value="General Question">General Inquiry</option>
					  <option value="Bug Report">Report A Bug</option>
					  <option value="Account Issue">Report an Account Issue</option>
					  <option value="Joining OLM">Become part of OLM</option>
					  <option value="Help">Help</option>
					</select>
					<label>Question</label>
					<textarea rows="6" class="span6" name="message[body]"></textarea>
				  </fieldset>
				  <fieldset class="actions">
				    <%= form.submit "Send" %>
				  </fieldset>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<div class="container">
	<div class="row">
		<div class="span7">
			<div class="well">
			  <h1>Why Should You Choose OLM?</h1>
			</div>
			<div class="well">
			  <p class="tab">So why exactly should you be so interested in our Online Library Management
			  system? Well the answer is quite simple: it is the best way to effectively read
			  and study. We provide an online system for managing books, and through our partnerships with
			  schools we effectively tailor our site to the needs of individuals whilst vastly
			  enriching available content.</p>
			  <p class="tab">We take the extra work out of ascertaining a book. Without OLM, if you want a new book for
			  a class you only have a few options: take time to drive to a library and check it out or fork over a lot of money. With our
			   system, the hassles of these options are eliminated. The partnerships with schools make content vast and affordable. There
			    is no reason to take the time to drive to a library, only to find out that they don't have the book you want. There is 
			    no worry about late fee's. Recurring notifications keep you updated on the status of books you requested or currently have 
			    checked out. And our limitless tools make the experience once the book is obtained, much more enjoyable and rewarding. </p>
			  <p class="tab">Once you get signed up through your participating school you can access the vast toolset present in OLM. The user page contains all the tools and functionalities that one would expect when visiting a physical library. This consists of tabs for checking out books, reserving books, requesting books, previewing books, and a list of books read or checked out. There is constant online support and help documents designed to aid in the use of OLM tools. There is the convenient search bar (in addition to the standard website search) that will aid users in searching for contents in a book. There are custom demographics that give the user a list of recently checked out books, with any brief notes and personal ratings, along with statistics on time spent reading, highlights made etc. Our tailored algorithms keep track of individuals tastes
			  and help make recommendations for more suited leisurely reading or study material.</p>
			  <p class="tab">Perhaps the most enticing features of OLM are those present when actually viewing a book. Among these are tools for adding, editing and deleting contents in a book (these edits are only local, and all changes made are kept in logs for easy rollback). There are tools for creating posted-notes on a page, and general notes on the book you are reading. There will is a tool for tagging pages which can be referred to later. There are editing tools, like those for highlighting text, changing fonts, etc. There will be template pages you can create for summarizing contents of a page, chapter etc.</p>
			  <p class="tab">In short, OLM is a simple and effective tool for students in school. It provides them with free access to a huge
			  repository of content, and gives them all the features necesarry for creating an ideal study environment. There are no late fee's,
			  no charges, and it is tailored to fit you. So stop waiting and sign up now!</p>
			</div>
		</div>
		<div class="span5">
			<ul class="thumbnails">  
        <li class="span5">  
          <div class="thumbnail">  
            <img src="/thumbnail.jpg" alt="Effective Learning" style="padding:10px;">  
            <div class="caption">  
              <h5>Endless Content Just a Click Away</h5>  
              <p>Sit back a check out a book for leisurely reading. Pick it yourself or have our system pick
              one for you based on your style. Find the latest text books and study materials with cutting 
              edge tools that make learning easy. Or even start creating your own content to give back to the community!
               The possibilities are endless!</p>  
              <p><a href="/users/new" class="btn btn-success">Get Started</a> <a href="#" class="btn btn-info">Participating Schools</a></p>  
            </div>  
          </div>  
        </li> 
			</ul>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class = "container">
	<div class = "row">
		<div class = "span5">
			<div class="well well-small">
				<h3>  Contact Us</h3>
				<ul class="nav nav-list"></ul>
				 </div>

	
				<div class="well well-small">
				 <address>
				  <strong>OLM, Inc.</strong><br>
				  777 Random Ave, Suite 666<br>
				  Tempe, Az, 85284<br>
				  <abbr title="Support">P:</abbr> (123) 456-7890
				</address>
				  <table class="table">
					  <thead><th>Founder</th> <th>Email</th> <th>Number</th></thead>
					   <tbody>
					    <tr>
					      <td>David Dunning</td>
					      <td>dcdunnin@asu.edu</td>
					      <td>(480)208-3077</td>
					    </tr>
					    <tr>
					      <td>Shantanu Bala</td>
					      <td>shantanu@asu.edu</td>
					      <td>(480)242-0876</td>
					    </tr>
					    <tr>
					      <td>Antonio Franchini</td>
					      <td>afranchi@asu.edu</td>
					      <td>(480)202-8084</td>
					    </tr>
					  </tbody>
				  </table>
			</div>
		</div>
		<div class = "span7">
			<div class="well well-small">
				<h3>Any Questions?</h3>
				<ul class="nav nav-list"></ul>
				 </div>
			<div class="well well-small">
				 <form>
				  <fieldset>
				  <label class="control-label" for="inputIcon">Name</label>
					  <div class="controls">
					    <div class="input-prepend">
					      <span class="add-on"><i class="icon-user" ></i></span>
					      <input class="span3" id="inputIcon" type="text" placeholder="John Smith">
					    </div>
					  </div>
				    <label class="control-label" for="inputIcon">Email address</label>
					  <div class="controls">
					    <div class="input-prepend">
					      <span class="add-on"><i class="icon-envelope" ></i></span>
					      <input class="span3" id="inputIcon" type="text" placeholder="example123@email.com">
					    </div>
					  </div>
				    <label>Nature of Email</label>
				    <select class ="span4">
					  <option>General Inquiry</option>
					  <option>Report A Bug</option>
					  <option>Report an Account Issue</option>
					  <option>Become part of OLM</option>
					  <option>Help</option>
					</select>
					<label>Question</label>
					<textarea rows="6" class="span6"></textarea>
				  </fieldset>
				  <div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn">Email!</button>
				    </div>
				  </div>
				</form>
			</div>
		</div>
	</div>
</div>

app/views/upload/fileform.html.erb
<div class="container">
  <div class="row">
    <div class="span2"></div>
    <div class="span8">
      <div class="well well-small wellBlue">
        <h3 class="text-center">Upload to OLM</h3>
      </div>
      <div class="well well-small text-center wellBlue">
	<%= form_tag("/upload/fileupload", multipart: true)  do %>

	<div id="user_nav">
		  <% if @badForm==true %>
	      	<ul>
	          <div class="alert alert-error">
	            <button type="button" class="close" data-dismiss="alert">&times;</button>
	            <strong>Warning!</strong>
	            <ul>
	                <p>You did not include all of the required fields!</p>
	      	    </ul>
	      	  </div>
	      <%end%>
			<% if flash[:notice] %>
			<div class="alert"><%= flash[:notice] %></div>
			<% end %>
		  <div class="field">
		    <%= label_tag :title %>
		    <%= text_field_tag :title, params[:title] %>
		  </div>
		  <div class="field">
		    <%= label_tag :author %>
		    <%= text_field_tag :author, params[:author] %>
		  </div>
		  <div class="field">
		    <%= label_tag "Cover (image file)" %>
		  	<%= file_field_tag 'cover' %>
		  </div>
		  <div class="field">
		    <%= label_tag "Book (PDF file)" %>
		  	<%= file_field_tag 'book' %>
		  </div>
		  <div class="actions"><%= submit_tag "Upload File" %></div>

	  <% end %>
	</div>
	<div class="span2"></div>
	</div>
	</div>
	</div>
</div>