config/routes.rb
OLM::Application.routes.draw do
  get "users/user"
  get "books/index"
  get "dashboard/index"
  get "static_pages/contact"
  get "static_pages/about"
  get "static_pages/faq"

  get "welcome/index"

  root 'welcome#index'

  get 'users/account' => 'users#account'
  post 'users/editaccount' => 'users#editaccount'
  get 'users/:new' => 'users#new'
  get 'login/:new' => 'login#new'
  post 'login/:new' => 'login#create'
  delete 'login/:new' => 'login#destroy'
  delete '/#' => 'login#destroy'

  get 'upload/pdfview' => 'upload#pdfview'
  get 'upload/fileform' => 'upload#fileform'
  get 'upload/search' => 'upload#search'
  post 'upload/fileupload' => 'upload#fileupload'

  get '/contact' => 'contact#new'
  post '/contact' => 'contact#create'

  Rails.application.routes.draw do
  resources :users # or resource :user for singular resources
  resources :login
  end

  namespace :admin do
    get "manage_users/list", to: 'manage_users#list', as: '/manage_users/list'
    get "manage_books/list", to: 'manage_books#list', as: '/manage_books/list'
    get 'dashboard/index', to: 'dashboard#show', as: '/'
    post 'manage_users/list'
    get 'add/new'  => 'add#new'
    post 'add/new' => 'add#create'
    post 'manage_books/list'
    post 'manage_books/delete'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates_presence_of :title, :on => :create
	validates_presence_of :author, :on => :create
	validates_presence_of :book, :on => :create
	validates_presence_of :cover, :on => :create

	def self.search_title(search)
		if search
			find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end

	def self.search_author(search)
		if search
			find(:all, :conditions => ['author LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_presence_of :first_name, :on => :create
	validates_presence_of :last_name, :on => :create
	validates_presence_of :zip, :on => :create
	validates_presence_of :username, :on => :create
	validates_presence_of :email, :on => :create
	validates_length_of :last_name, :maximum => 30, :message => "last name to long!"
	validates_length_of :first_name, :maximum => 15, :message => "first name to long!"
	validates_length_of :username, :within => 6..20, :too_long => "pick a shorter name", :too_short => "pick a longer name"
    validates_length_of :zip, :minimum => 5, :too_short => "please enter at least 5 characters"
    validates_length_of :password, :minimum => 8 ,:maximum => 32, :within => 8..32,:too_short => 'way too short', :too_long => 'way to long'
    validates_uniqueness_of :username, :email, :case_sensitive => false
end

app/controllers/admin/add_controller.rb
class Admin::AddController < ApplicationController
  def new
    if current_user != nil && current_user.admin?
      @admin = User.new
    else
      redirect_to root_path
    end
  end

  def create
	  if current_user != nil && current_user.admin?
	    def my_params
	      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country, :admin)
	    end 
	    @admin = User.new(my_params)
	    @admin.admin = true;
	    if @admin.save
	      redirect_to "/admin/dashboard/index", :notice => "Signed up!"
	    else
	      render "/admin/add/new"
	    end
	   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #force_ssl
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
  	@badForm=false;
  	user = User.find_by_email(params[:email])
  	if user == nil
  		user = User.find_by_username(params[:email])
  	end
	if user && user.authenticate(params[:password])
	  @badForm=false;
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Logged in!"
	else
	  @badForm=true;
	  flash.now.alert = "Invalid email or password"
	  render "new"
	end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def faq
  end
  
  def about
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def pdfview
		@book = Book.find(params[:id])
	end

	def search
		@title_books = Book.search_title(params[:q])
		@author_books = Book.search_author(params[:q])
	end

	def fileupload
		uploaded_io = params[:book]
		uploaded_io2 = params[:cover]
		File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb+') do |file|
			file.write(uploaded_io.read)
		end
		File.open(Rails.root.join('public', 'uploads', uploaded_io2.original_filename), 'wb+') do |file|
			file.write(uploaded_io2.read)
		end

		book_params = {
			:title => params[:title],
			:author => params[:author],
			:book => params[:book].original_filename,
			:cover => params[:cover].original_filename,
		}

		book = Book.new(book_params)

		if book.save
			redirect_to "/upload/pdfview?id=" + String(book.id)
		else
			render "fileform"
		end
	end

	def fileform
		@message = "Hello, World!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit]

  def account
    @user = current_user()
    if @user == nil then
      redirect_to "/"
    end
  end

  def update
    @user = current_user()
    if @user == nil then
      redirect_to "/"
    end
    def user_params
      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country)
    end
    @user = User.update(params[:id], user_params)
    render "account"
  end

  def new
    @user = User.new
  end

  def create
    def user_params
      params.require(:user).permit(:first_name, :last_name, :school, :zip, :birth, :username, :email, :password, :password_confirmation, :country)
    end
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/add_helper.rb
module Admin::AddHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OLM</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/#">Online Library Management</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "About", "/static_pages/about"%></li>
          <li><%= link_to "Contact", "/contact" %></li>
          <li><%= link_to "FAQ", "/static_pages/faq" %></li>
          <li>
            <div class="btn-group span2">
            <button type="button" class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
              Accounts <span class="caret-inverse"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <% if current_user %>
                <li>
                  <%if current_user != nil && current_user.admin?%>
                    <%= link_to "Admin Account", admin_url%>
                  <%else%>
                    <a href="/users/account">My Account</a>
                  <%end%>
                </li>
                <li><%= link_to "Logout", {:controller=> "/login", :action=> "destroy"}, :method => :delete%></li>
              <%else%>
                <li><a href="/login/new">Sign In</a></li>
                <li><a href="/users/new">Register</a></li>
              <%end%>
            </ul>
          </div>
          </li>

        </ul>
      </div>
      </form>
      <form class="navbar-search pull-right" action="/upload/search">
      <div class="input-append">
  		<input type="text" class="text" placeholder="Search" name="q">
      <button type="submit" class="btn"><i class="icon-search"></i></button>
      </div>
	  </form>
    </div>
  </div>
</div>
<div class="container">
  <% if flash[:notice] %>
  <div class="alert"><%= flash[:notice] %></div>
  <% end %>
	<div class="row">
		<div class="span9"><%= yield %></div>
		<div class="span3"></div>
</div>
</body>
</html>